language: node_js

node_js:
  - "node"
  - "7"

branches:
  only:
    - master
 
script:
 - npm install --save-dev nyc mocha sinon mongoose
 - npm run test
 - cd bot; npm run test
 - cd ../productSearch; npm run test